version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run tests
          command: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test