export const Typography = Object.freeze({
  FONT_FAMILIES: ["Plus Jakarta Sans:400,600,700", "JetBrains Mono"],
  DEFAULT_FONT: "Plus Jakarta Sans",
  MONOSPACE_FONT: "JetBrains Mono",
  TEXT_SHADOW: "0.25rem 0.25rem 2rem rgba(0, 0, 0, 0.3)",
  H1: "h1",
  H2: "h2",
  H3: "h3",
  H4: "h4",
  H5: "h5",
  H6: "h6",
  BOLD: "bold",
  SECTION_TITLE_TAG: "h3",
  CARD_TITLE_TAG: "h5",
  SUBHEADING_TAG: "h4",
});
